### ISSUE TITLE
Install failed with python 2.7

### ISSUE THREAD

**Issue by azfayel** [HurricaneLabs/machinae#24]
Hi,
Can you give me the requirements for installing the lastest version of machine.
regards,

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in 
run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundl
e=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1235, in prepare_file
s
    req_to_install.assert_source_matches_version()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 465, in assert_source
_matches_version
    % (display_path(self.source_dir), version, self))
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 71, in display_path
    if path.startswith(os.getcwd() + os.path.sep):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7: ordinal 
not in range(128)

[installation.zip](https://github.com/HurricaneLabs/machinae/files/237206/installation.zip)

**Comment by mcm** [comment]
I can but you probably won't like the answer. We only support Python 3, unfortunately.
