### ISSUE TITLE
Error on a clean system install with machinae 1.4.0

### ISSUE THREAD

**Issue by g03l** [HurricaneLabs/machinae#29]
Hi,
I'm not sure what the issue is, but I'm getting this error output when trying to run for the first time after a clean install via "pip3 install machinae". Can you help please?
#######
user@data:/opt/machinae$ machinae -c /opt/machinae/machinae.yml -f /opt/machinae/machinae.txt
Traceback (most recent call last):
  File "/usr/local/bin/machinae", line 9, in <module>
    load_entry_point('machinae==1.4.0', 'console_scripts', 'machinae')()
  File "/usr/local/lib/python3.4/dist-packages/machinae/cmd.py", line 209, in main
    cmd.run()
  File "/usr/local/lib/python3.4/dist-packages/machinae/cmd.py", line 178, in run
    if len(self.conf) == 0:
  File "/usr/local/lib/python3.4/dist-packages/machinae/cmd.py", line 68, in conf
    conf = utils.safe_load(f)
  File "/usr/local/lib/python3.4/dist-packages/machinae/utils.py", line 35, in safe_load
    return yaml.load(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.4/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.4/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.4/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.4/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.4/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.4/dist-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.4/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.4/dist-packages/yaml/scanner.py", line 580, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/opt/machinae/machinae.yml", line 7, column 19

**Comment by mcm** [comment]
@g03l are you using the config file straight out of the repository? Can you post it here or a pastebin or something so we can take a look?

**Comment by g03l** [comment]
<embarrassed smiley>
ekhm... I'm sorry - I copied the config file not in a raw format so it included all of the html tags...
Now everything is fine.
Sorry to bother you!

All the best!
