### ISSUE TITLE
WSL not supported

### ISSUE THREAD

**Issue by userrrrrrrr** [HurricaneLabs/machinae#65]
When running machinae in WSL i get the following traceback when trying to execute:

Traceback (most recent call last):
  File "/home/user/venvs/dev/bin/machinae", line 11, in <module>
    load_entry_point('machinae==1.4.9', 'console_scripts', 'machinae')()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/machinae/cmd.py", line 218, in main
    cmd.run()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/machinae/cmd.py", line 185, in run
    if not self.conf:
  File "/home/user/venvs/dev/lib/python3.8/site-packages/machinae/cmd.py", line 71, in conf
    conf = utils.safe_load(f)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/machinae/utils.py", line 37, in safe_load
    return yaml.load(*args, **kwargs)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/scanner.py", line 227, in fetch_more_tokens
    return self.fetch_alias()
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/scanner.py", line 610, in fetch_alias
    self.tokens.append(self.scan_anchor(AliasToken))
  File "/home/user/venvs/dev/lib/python3.8/site-packages/yaml/scanner.py", line 922, in scan_anchor
    raise ScannerError("while scanning an %s" % name, start_mark,
yaml.scanner.ScannerError: while scanning an alias
  in "machinae.yml", line 1418, column 14
expected alphabetic or numeric character, but found '*'
  in "machinae.yml", line 1418, column 15

outside venv same error occurs.

**Comment by mcm** [comment]
Can you share what your machinae.yml file looks like?

**Comment by basedfir** [comment]
I have a similar issue, with mine however it just ends up saying "machinae: command not found" despite installing from both GH and pip. 
Will check path.

**Comment by basedfir** [comment]
Yea so i had to go into site packages to launch machinae,
also this is what happens when i do via WSL

Traceback (most recent call last):
  File "/home/kbase/.local/bin/machinae", line 8, in <module>
    sys.exit(main())
  File "/home/kbase/.local/lib/python3.8/site-packages/machinae/cmd.py", line 218, in main
    cmd.run()
  File "/home/kbase/.local/lib/python3.8/site-packages/machinae/cmd.py", line 185, in run
    if not self.conf:
  File "/home/kbase/.local/lib/python3.8/site-packages/machinae/cmd.py", line 71, in conf
    conf = utils.safe_load(f)
  File "/home/kbase/.local/lib/python3.8/site-packages/machinae/utils.py", line 37, in safe_load
    return yaml.load(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 227, in fetch_more_tokens
    return self.fetch_alias()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 610, in fetch_alias
    self.tokens.append(self.scan_anchor(AliasToken))
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 922, in scan_anchor
    raise ScannerError("while scanning an %s" % name, start_mark,
yaml.scanner.ScannerError: while scanning an alias
  in "/etc/machinae.yml", line 1418, column 14
expected alphabetic or numeric character, but found '*'
  in "/etc/machinae.yml", line 1418, column 15

**Comment by basedfir** [comment]
Update: Appears to be happening on actual VM as well - running Debian or Arch on VMW

**Comment by bloomer1016** [comment]
Had the same issue on clean Ubuntu image. Turns out that the issue was spacing under the "Greynoise" section - in particular the 'headers' and 'key' were not spaced correctly after removing the comment. Just had to backspace 1 and it was fixed. Hope that helps.

**Comment by cylaris** [comment]
Many thanks @bloomer1016 !
