### ISSUE TITLE
Package not found error

### ISSUE THREAD

**Issue by jawaharas** [HurricaneLabs/machinae#67]
Hello,

I've installed the 'Machinae' successfully in Mac OS 13.3.1 using the below command. However, I am getting 'package not found' error as shown below. 

_pip3 install git+https://github.com/HurricaneLabs/machinae.git_

```
machinae <ip_address>
Traceback (most recent call last):
  File "/Users/user1/Library/Python/3.9/bin/machinae", line 8, in <module>
    sys.exit(main())
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/machinae/cmd.py", line 218, in main
    cmd.run()
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/machinae/cmd.py", line 202, in run
    output = outputs.MachinaeOutput.get_formatter(fmt).run(self.results)
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/machinae/outputs.py", line 46, in run
    for row in result_sets:
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/machinae/cmd.py", line 129, in results
    scraper = Site.from_conf(site_conf, creds=creds, proxies=proxies)  # , verbose=self.verbose)
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/machinae/sites/__init__.py", line 48, in from_conf
    from . import csv, html, rss, json, ipwhois
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/machinae/sites/csv.py", line 7, in <module>
    from .base import HttpSite
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/machinae/sites/base.py", line 9, in <module>
    import magic
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/magic/__init__.py", line 18, in <module>
    from magic.identify import Magic, MagicError
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/magic/identify.py", line 16, in <module>
    from magic import api
  File "/Users/user1/Library/Python/3.9/lib/python/site-packages/magic/api.py", line 22, in <module>
    raise ImportError('Unable to find magic library')
ImportError: Unable to find magic library
```

**Comment by Lester0142** [comment]
https://github.com/HurricaneLabs/machinae/issues/27#issuecomment-502208047

**Comment by cschmidt0121** [comment]
Hey there, I'm not encountering this myself but I'm guessing I already have libmagic installed from some other dependency. You likely just need to install libmagic and the easiest way to do that on a mac is `brew install libmagic`
